# Generated by Django 5.2.1 on 2025-09-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manage_book_tbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('total_copies', models.CharField(max_length=100)),
                ('available_copies', models.CharField(max_length=100)),
            ],
        ),
    ]
