# Generated by Django 5.2.1 on 2025-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_manage_book_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='manage_member_tbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('members_date', models.CharField(max_length=100)),
            ],
        ),
    ]
