# Generated by Django 5.2.1 on 2025-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_manage_member_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue_return_tbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookid', models.IntegerField()),
                ('memberid', models.IntegerField()),
                ('duedate', models.CharField(max_length=100)),
                ('issuedate', models.CharField(max_length=100)),
                ('returndate', models.CharField(max_length=100)),
                ('fine', models.CharField(max_length=100)),
            ],
        ),
    ]
