# Generated by Django 5.2.1 on 2025-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_issue_return_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_book_tbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookid', models.IntegerField()),
                ('memberid', models.IntegerField()),
                ('returndate', models.CharField(max_length=100)),
            ],
        ),
    ]
