# Generated by Django 5.2.1 on 2025-09-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_return_book_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_return_tbl',
            name='bookid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issue_return_tbl',
            name='memberid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='return_book_tbl',
            name='bookid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='return_book_tbl',
            name='memberid',
            field=models.CharField(max_length=100),
        ),
    ]
